# Generated by Django 4.1.7 on 2023-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('qln', models.CharField(max_length=50)),
                ('mob', models.IntegerField()),
                ('img', models.CharField(max_length=850)),
            ],
        ),
    ]
